### ISSUE TITLE
error in showing fansy show

### ISSUE THREAD

**Issue by mohsenzamani22** [faruktoptas/FancyShowCaseView#143]
when i want to start the fansy show 
this error comes up
final FancyShowCaseView view1 = new FancyShowCaseView.Builder(mActivity)
                    .title("first show")
                    .focusOn((ImageView) mValues.get(0))
                    .focusBorderColor(Color.GREEN)
                    .focusBorderSize(10)
                    .enableTouchOnFocusedView(false)
                    .backgroundColor(Color.parseColor("#AAff0000"))
                    .showOnce(mShowCase.get(0))
                    .build();
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at me.toptas.fancyshowcase.FancyShowCaseView$Builder.<init>(Unknown Source:2)
        at mohsen.zamani.store.Util.ShowCaseUtils.showImageCityMainPage(ShowCaseUtils.java:27)
        at mohsen.zamani.store.Activities.City.CityMainActivity.presentShowcaseSequence(CityMainActivity.java:291)
        at mohsen.zamani.store.Activities.City.CityMainActivity.loadShowCase(CityMainActivity.java:78)
        at mohsen.zamani.store.Activities.City.CityMainActivity.loadLayout(CityMainActivity.java:101)
        at mohsen.zamani.store.Activities.City.CityMainActivity.onStart(CityMainActivity.java:84)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
        at android.app.Activity.performStart(Activity.java:7200)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/base.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_dependencies_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_resources_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_0_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_1_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_2_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_3_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_4_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_5_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_6_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_7_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_8_apk.apk", zip file "/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/lib/arm, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/base.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 18 more
    	Suppressed: java.io.IOException: No original dex files found for dex location (arm) /data/app/mohsen.zamani.store-9S6lYww1JErwGwpE2ex7lQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:678)
E/AndroidRuntime:     at android.app.LoadedApk.getClassLoader(LoadedApk.java:711)
        at android.app.LoadedApk.getResources(LoadedApk.java:944)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5943)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        		... 6 more

**Comment by faruktoptas** [comment]
Can you try this:
https://stackoverflow.com/questions/44197521/gradle-project-java-lang-noclassdeffounderror-kotlin-jvm-internal-intrinsics

**Comment by faruktoptas** [comment]
@mohsenzamani22 solved the problem?

**Comment by mohsenzamani22** [comment]
> @mohsenzamani22 solved the problem?

yes
