### ISSUE TITLE
Crash on android 9.0 when call hide()

### ISSUE THREAD

**Issue by s675660665** [faruktoptas/FancyShowCaseView#144]
### Fatal Exception: java.lang.IllegalStateException: Cannot start this animator on a detached view!
       at android.view.RenderNode.addAnimator(RenderNode.java:830)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:295)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:280)
       at android.animation.RevealAnimator.(RevealAnimator.java:37)
       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:71)
       at me.toptas.fancyshowcase.FancyShowCaseView.g(FancyShowCaseView.java:21)
       at me.toptas.fancyshowcase.FancyShowCaseView.hide(FancyShowCaseView.java:16)

**Comment by faruktoptas** [comment]
@s675660665 how do you show the view? Are you trying to hide it after activity finish?

**Comment by s675660665** [comment]
This issue occur when new two view to one filed, solved now.
