### ISSUE TITLE
NoClassDefFoundError: Class not found using the boot class loader; no stack available

### ISSUE THREAD

**Issue by iman2420** [faruktoptas/FancyShowCaseView#148]
In some device i got this error:

       `E/UncaughtException: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at me.toptas.fancyshowcase.FancyShowCaseView$Builder.<init>(FancyShowCaseView.kt)
        at package.activities.HomeActivity.lambda$fillShowcaseQueue$15$HomeActivity(HomeActivity.java:761)
        at package.activities.-$$Lambda$HomeActivity$7XORiKh8hXivvgazjwz1KrplNBE.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5319)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/package-2/base.apk"],nativeLibraryDirectories=[/data/app/package-2/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at me.toptas.fancyshowcase.FancyShowCaseView$Builder.<init>(FancyShowCaseView.kt) 
        at package.activities.HomeActivity.lambda$fillShowcaseQueue$15$HomeActivity(HomeActivity.java:761) 
        at package.activities.-$$Lambda$HomeActivity$7XORiKh8hXivvgazjwz1KrplNBE.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5319) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
    	Suppressed: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 12 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
      E/AndroidRuntime: FATAL EXCEPTION: main
    Process: package, PID: 12344
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at me.toptas.fancyshowcase.FancyShowCaseView$Builder.<init>(FancyShowCaseView.kt)
        at package.activities.HomeActivity.lambda$fillShowcaseQueue$15$HomeActivity(HomeActivity.java:761)
        at package.activities.-$$Lambda$HomeActivity$7XORiKh8hXivvgazjwz1KrplNBE.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5319)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/package-2/base.apk"],nativeLibraryDirectories=[/data/app/package-2/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at me.toptas.fancyshowcase.FancyShowCaseView$Builder.<init>(FancyShowCaseView.kt) 
        at package.activities.HomeActivity.lambda$fillShowcaseQueue$15$HomeActivity(HomeActivity.java:761) 
        at package.activities.-$$Lambda$HomeActivity$7XORiKh8hXivvgazjwz1KrplNBE.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5319) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
    	Suppressed: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 12 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
`

**Comment by faruktoptas** [comment]
@iman2420 On what Android versions you got this error?
 Is kotlin configured on your project?

**Comment by antailbaxt3r** [comment]
`implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.31'
    implementation 'nl.dionsegijn:konfetti:1.1.2'`

Add these lines to your build.gradle dependencies. Manually adding the Kotlin libraries worked for me.

**Comment by fahadfa** [comment]
> In some device i got this error:
> 
>    `E/UncaughtException: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
>     at me.toptas.fancyshowcase.FancyShowCaseView$Builder.<init>(FancyShowCaseView.kt)
>     at package.activities.HomeActivity.lambda$fillShowcaseQueue$15$HomeActivity(HomeActivity.java:761)
>     at package.activities.-$$Lambda$HomeActivity$7XORiKh8hXivvgazjwz1KrplNBE.run(lambda)
>     at android.os.Handler.handleCallback(Handler.java:739)
>     at android.os.Handler.dispatchMessage(Handler.java:95)
>     at android.os.Looper.loop(Looper.java:135)
>     at android.app.ActivityThread.main(ActivityThread.java:5319)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at java.lang.reflect.Method.invoke(Method.java:372)
>     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
>  Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/package-2/base.apk"],nativeLibraryDirectories=[/data/app/package-2/lib/arm64, /vendor/lib64, /system/lib64]]
>     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
>     at me.toptas.fancyshowcase.FancyShowCaseView$Builder.<init>(FancyShowCaseView.kt) 
>     at package.activities.HomeActivity.lambda$fillShowcaseQueue$15$HomeActivity(HomeActivity.java:761) 
>     at package.activities.-$$Lambda$HomeActivity$7XORiKh8hXivvgazjwz1KrplNBE.run(lambda) 
>     at android.os.Handler.handleCallback(Handler.java:739) 
>     at android.os.Handler.dispatchMessage(Handler.java:95) 
>     at android.os.Looper.loop(Looper.java:135) 
>     at android.app.ActivityThread.main(ActivityThread.java:5319) 
>     at java.lang.reflect.Method.invoke(Native Method) 
>     at java.lang.reflect.Method.invoke(Method.java:372) 
>     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016) 
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
> 	Suppressed: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
>     at java.lang.Class.classForName(Native Method)
>     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
>     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
>     		... 12 more
>  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
>   E/AndroidRuntime: FATAL EXCEPTION: main
> Process: package, PID: 12344
> java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
>     at me.toptas.fancyshowcase.FancyShowCaseView$Builder.<init>(FancyShowCaseView.kt)
>     at package.activities.HomeActivity.lambda$fillShowcaseQueue$15$HomeActivity(HomeActivity.java:761)
>     at package.activities.-$$Lambda$HomeActivity$7XORiKh8hXivvgazjwz1KrplNBE.run(lambda)
>     at android.os.Handler.handleCallback(Handler.java:739)
>     at android.os.Handler.dispatchMessage(Handler.java:95)
>     at android.os.Looper.loop(Looper.java:135)
>     at android.app.ActivityThread.main(ActivityThread.java:5319)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at java.lang.reflect.Method.invoke(Method.java:372)
>     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
>  Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/package-2/base.apk"],nativeLibraryDirectories=[/data/app/package-2/lib/arm64, /vendor/lib64, /system/lib64]]
>     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
>     at me.toptas.fancyshowcase.FancyShowCaseView$Builder.<init>(FancyShowCaseView.kt) 
>     at package.activities.HomeActivity.lambda$fillShowcaseQueue$15$HomeActivity(HomeActivity.java:761) 
>     at package.activities.-$$Lambda$HomeActivity$7XORiKh8hXivvgazjwz1KrplNBE.run(lambda) 
>     at android.os.Handler.handleCallback(Handler.java:739) 
>     at android.os.Handler.dispatchMessage(Handler.java:95) 
>     at android.os.Looper.loop(Looper.java:135) 
>     at android.app.ActivityThread.main(ActivityThread.java:5319) 
>     at java.lang.reflect.Method.invoke(Native Method) 
>     at java.lang.reflect.Method.invoke(Method.java:372) 
>     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016) 
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
> 	Suppressed: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
>     at java.lang.Class.classForName(Native Method)
>     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
>     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
>     		... 12 more
>  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
> ```
> 
> `

**Comment by faruktoptas** [comment]
@fahadfa you should add kotlin dependency to your project.
`compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"`
