### ISSUE TITLE
App crash when try to show showcase.

### ISSUE THREAD

**Issue by husnain92** [faruktoptas/FancyShowCaseView#92]
I have implemented showcase queue on multiple screens but some times it crash with following log. I clearly shows that when I try to start showcase queue it crash app.  Please help me fix this issue.
Thanks

mContext.runOnUiThread(new Runnable() {
                    @Override
                    public void run() {

                        fancyShowCaseQueue = new FancyShowCaseQueue();
                        fancyShowCaseQueue
                                .add(showcase1)
                                .add(showcase2)
                                .add(showcase3);
                        if (fancyShowCaseQueue != null) {
                            fancyShowCaseQueue.show();   //  CRASH ON THIS LINE
                            MainActivity.isTutShown = true;
                        }
                    }
                });

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'me.toptas.fancyshowcase.c me.toptas.fancyshowcase.FancyShowCaseView.getDismissListener()' on a null object reference
       at me.toptas.fancyshowcase.FancyShowCaseQueue.show(SourceFile:42)
       at android.os.Handler.handleCallback(Handler.java:755)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by faruktoptas** [comment]
@husnain92 can you share the code that you create showcases (showcase1, showcase2, showcase3)? It seems that when you start the queue some of the showcases are still null.

**Comment by husnain92** [comment]
@faruktoptas   Yeah it was showcase was null in some cases. I fixed it after you pointed issue cause.
Thank you so much. :+1:
