### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by ornolisvt** [faruktoptas/FancyShowCaseView#97]
I created a binding to C # for this library to use with Xamarin Android. I created a queue with three elements as follows:

            var imgScan = FindViewById<ImageView>(Resource.Id.img_scan);
            var b1 = new FancyShowCaseView.Builder(this)
                .FocusOn(imgScan)
                .Title("Escanea el código QR")
                .Build();

            var autoComplete = FindViewById<AutoCompleteTextView>(Resource.Id.edt_search);
            var b2 = new FancyShowCaseView.Builder(this)
                .FocusOn(autoComplete)
                .Title("Busque la tienda a la cual desea pagar")
                .FocusShape(FocusShape.RoundedRectangle)
                .RoundRectRadius(45)
                .FocusCircleRadiusFactor(2)
                .Build();

            var rlCards = FindViewById<RelativeLayout>(Resource.Id.rl_card_selection);
            var b3 = new FancyShowCaseView.Builder(this)
                .FocusOn(rlCards)
                .Title("Seleccione la tarjeta deslizando hacia los lados")
                .TitleStyle(Resource.Style.MyTitleStyle, (int)GravityFlags.Top | (int)GravityFlags.Center)
                .FocusShape(FocusShape.RoundedRectangle)
                .FocusBorderColor(Color.ParseColor("#0390AE"))
                .FocusBorderSize(10)
                .BackgroundColor(Color.ParseColor("#cc0390AE"))
                //.FocusCircleRadiusFactor(40)
                .Build();

            _mQueue = new FancyShowCaseQueue()
                .Add(b1)
                .Add(b2)
                .Add(b3);

Then in an action button use

               _mQueue.Show();

When calling Show() several times the memory usage grows until it causes this crash

It was tested on a Samsung Galaxy S6 Edge with Android 7.0

The crash reported:

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 14192652 byte allocation with 289072 free bytes and 282KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:915)
       at me.toptas.fancyshowcase.FancyImageView.onDraw(FancyImageView.java:138)
       at android.view.View.draw(View.java:18324)
       at android.view.View.updateDisplayListIfDirty(View.java:17302)
       at android.view.View.draw(View.java:18086)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17297)
       at android.view.View.draw(View.java:18086)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17297)
       at android.view.View.draw(View.java:18086)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17297)
       at android.view.View.draw(View.java:18086)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.draw(View.java:18327)
       at com.android.internal.policy.DecorView.draw(DecorView.java:919)
       at android.view.View.updateDisplayListIfDirty(View.java:17302)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:692)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:698)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:806)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3135)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2931)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2523)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7098)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
       at android.view.Choreographer.doFrame(Choreographer.java:638)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Please can you help me?

**Comment by faruktoptas** [comment]
@ornolisvt it is difficult to find OOM crashes. Can you get a memory dump to see which objects allocate the memory?
There may be some object instances that can't be collected by GC. You have to find out these objects.

**Comment by ornolisvt** [comment]
Hello, I made some changes to the code and generated the library again, in this case it frees the resources. The main change has been in the FancyImageView file:
```
     @Override
     protected void onDetachedFromWindow() {
         super.onDetachedFromWindow();
         if (mBitmap! = null && !mBitmap.isRecycled())
         {
             mBitmap.recycle();
             mBitmap = null;
         }
     }}
```
Thanks

**Comment by faruktoptas** [comment]
Great :)
Can you create a pull request? I will check then merge it.

**Comment by ornolisvt** [comment]
Ok, in the night I will make the pull request with the changes

**Comment by faruktoptas** [comment]
Thanks @ornolisvt

**Comment by rkarimi88** [comment]
Hi again :)
Have you created the pull request of this issue and update the library?

I have the same problem in Android 7. Is there any way to solve the problem without changing the lib, & just by adding some code? which objects should I clean instead of GC? Are they b1, b2 & b3 (in this example)?

**Comment by faruktoptas** [comment]
Hi @rkarimi88 I've merged but not released yet. There will be a new release today.

**Comment by faruktoptas** [comment]
Her it is :)
https://github.com/faruktoptas/FancyShowCaseView/releases/tag/1.0.1

**Comment by rkarimi88** [comment]
Thanks for you consideration :)
